parameters:
    #Repositories classes
    tree.repository.class: 'App\TreeBundle\Entity\TreeRepository'
    tree.repository.entity: 'App\TreeBundle\Entity\Tree'
    node.repository.class: 'App\TreeBundle\Entity\NodeRepository'
    node.repository.entity: 'App\TreeBundle\Entity\Node'
    #Services classes
    tree.service.class: 'App\TreeBundle\Services\TreeService'
    node.service.class: 'App\TreeBundle\Services\NodeService'
services:
    tree.repository:
        class: %tree.repository.class%
        public: false
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [%tree.repository.entity%]
    tree.service:
        class: %tree.service.class%
        arguments: ['@tree.repository']
        scope: request
    node.repository:
        class: %node.repository.class%
        public: false
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [%node.repository.entity%]
    node.service:
        class: %node.service.class%
        arguments: ['@node.repository']
        scope: request